### ISSUE TITLE
Bundle or link to cisco_epc module

### ISSUE THREAD

**Issue by urma** [rfdslabs/Mimosa-Framework#3]
When running Mimosa daemon (`mimosad.py`), the script complains about missing module `cisco_epc`:

```
$ python mimosad.py 
Traceback (most recent call last):
  File "mimosad.py", line 13, in <module>
    from cisco_epc import start_epc, stop_epc, collect_epc
ImportError: No module named cisco_epc
```

`grep` indicates the module source is not part of the Mimosa project and PyPI does not include any references to it (https://pypi.python.org/pypi?%3Aaction=search&term=cisco_epc&submit=search).

**Comment by rfdslabs** [comment]
Updated.
